version: '3'
services:
 db:
  image: postgres
  restart: always
  environment:
   MYSQL_DATABASE: 'db'
   POSTGRES_USER: 'root'
   POSTGRES_PASSWORD: 'password'
  ports:
   - '5432:5432'
  expose:
   - '5432'
  volumes:
   - postgresqlvol:/var/lib/postgresql/data
  networks:
   - postgresqlnet
volumes:
  postgresqlvol:
networks:
  postgresqlnet: {}

