version: '3'
services:
 db:
  image: postgres:9.4.0
  restart: always
  container_name: postgres9dot4dot0
  environment:
   POSTGRES_USER: 'root'
   POSTGRES_PASSWORD: 'password'
  ports:
   - '5432:5432'
  expose:
   - '5432'
  volumes:
   - postgresqlvolv9:/var/lib/postgresql/data
  networks:
   - postgresqlnetv9
volumes:
  postgresqlvolv9:
networks:
  postgresqlnetv9: {}

