version: '3'
services:
 localdatabase:
  image: mysql:latest
  restart: always
  environment:
   MYSQL_DATABASE: 'db'
   MYSQL_USER: 'root'
   MYSQL_PASSWORD: 'password'
   MYSQL_ROOT_PASSWORD: 'password'
  ports:
   - '3306:3306'
  expose:
   - '3306'
  volumes:
   - mysqlserver:/var/lib/mysql
  networks:
   - sqlnetwork
volumes:
  mysqlserver:
networks:
  sqlnetwork: {}

